const CopyPlugin = require("copy-webpack-plugin");
const path = require("path");

module.exports = {
  entry: "./dist/index.js", // Specify the entry file generated by TypeScript
  output: {
    filename: "bundle.js", // Specify the output file name
    path: path.resolve(__dirname, "dist"), // Specify the output directory
  },
  mode: "development",
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: "dist",
        },
      ],
    }),
  ],
  devServer: {
    port: 8080,
    liveReload: true,
  },
};
